management:
  newrelic:
    metrics:
      export:
        apiKey: "your-api-key"
        accountId: "your-account-id"
thread:
  pool:
    size: 4
entity:
  package:
    path: com.b2c.prototype.modal.entity
spring:
  web:
    locale: en
  messages:
    basename: ib18n
enums:
  brands:
    - value: HP
      label: "HP"
    - value: APPLE
      label: "APPLE"
    - value: ANDROID
      label: "ANDROID"
#  countTypes: LIMITED, UNLIMITED
#  countryPhoneCodes: +48
#  countries: POLAND
  currencies:
    - value: "USD"
      label: "USD"
    - value: "PLN"
      label: "PLN"
    - value: "EUR"
      label: "EUR"
#  deliveryTypes: IN_POST, COURIER
#  itemStatuses: NEW, EXIST, COMING_SOON, OUT_OF_STOCK
#  itemTypes: TECHNIQUE
#  messageStatuses: unread, read, delete
#  messageTypes: SYSTEM
#  optionGroups: TECHNIQUE
#  orderStatuses: NEW, PENDING, COMPLETE, TERMINATED
#  paymentMethods: CARD, CASH, BLIK
  ratings: 1, 2, 3, 4, 5
  categories:
    - name: "Electronics"
      sub:
        - name: "Computers"
          sub:
            - name: "Laptops"
            - name: "Desktops"
